{% set name = "betsee" %}
{% set version = "0.9.2.0" %}
{% set version_list = version.split('.') %}
{% set sha256 = "62a8c63c8ddad29bcd8c88bcda960db3c2d28493c19192374dbb25fba1eb8e23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - betsee = betsee.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools >=3.3
    - pip
  run:
    - python >=3.5
    - setuptools >=3.3
    - betse >={{ version_list[0] }}.{{ version_list[1] }}.{{ version_list[2] }}
    - pyside2

test:
  imports:
    - betsee
    - betsee.cli
    - betsee.lib
    - betsee.util
  commands:
    - betsee --help
    - betsee --version

about:
  home: https://gitlab.com/betse/betsee
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BETSEE, the BioElectric Tissue Simulation Engine Environment
  description: |
    BETSEE (BioElectric Tissue Simulation Engine Environment) is the open-source
    cross-platform graphical user interface (GUI) for BETSE, a finite volume simulator for
    2D computational multiphysics problems in the life sciences – including electrodiffusion,
    electro-osmosis, galvanotaxis, voltage-gated ion channels, gene regulatory networks, and
    biochemical reaction networks (e.g., metabolism). Like BETSE, BETSEE is portably
    implemented in pure Python 3, continuously stress-tested with GitLab-CI × Appveyor +
    py.test, and permissively distributed under the BSD 2-clause license.
  doc_url: https://www.dropbox.com/s/n8qfms2oks9cvv2/BETSE04_Documentation_Dec1st2016.pdf?dl=0
  dev_url: https://gitlab.com/betse/betsee

extra:
  recipe-maintainers:
    - leycec
