{% set name = "betsee" %}
{% set version = "1.0.0.0" %}
{% set version_list = version.split('.') %}
{% set sha256 = "5053eaf5c1ae720eb9ad9edc8655e9a6f474e221d4eeb10482fd272d80a4767c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - betsee = betsee.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools >=3.3
    - pip
  run:
    - python >=3.5
    - setuptools >=3.3
    - betse >={{ version_list[0] }}.{{ version_list[1] }}.{{ version_list[2] }}
    - pyside2

test:
  imports:
    - betsee
    - betsee.cli
    - betsee.lib
    - betsee.util

  #FIXME: Reenable all of the following functional tests as soon as feasible. These tests
  #*MUST* be temporarily disabled until the docker image used by CircleCI is revised to
  #include the mandatory "mesa-libGL" dependency installing the "libGL.so.1" shared library
  #required by Qt at runtime. See also:
  #    https://github.com/conda-forge/betsee-feedstock/pull/4
  #    https://circleci.com/gh/conda-forge/betsee-feedstock/14?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

  # commands:
  #   - betsee --help
  #   - betsee --version

about:
  home: https://gitlab.com/betse/betsee
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BETSEE, the BioElectric Tissue Simulation Engine Environment
  description: |
    BETSEE (BioElectric Tissue Simulation Engine Environment) is the open-source
    cross-platform graphical user interface (GUI) for BETSE, a finite volume simulator for
    2D computational multiphysics problems in the life sciences – including electrodiffusion,
    electro-osmosis, galvanotaxis, voltage-gated ion channels, gene regulatory networks, and
    biochemical reaction networks (e.g., metabolism). Like BETSE, BETSEE is portably
    implemented in pure Python 3, continuously stress-tested with GitLab-CI × Appveyor +
    py.test, and permissively distributed under the BSD 2-clause license.
  doc_url: https://www.dropbox.com/s/n8qfms2oks9cvv2/BETSE04_Documentation_Dec1st2016.pdf?dl=0
  dev_url: https://gitlab.com/betse/betsee

extra:
  recipe-maintainers:
    - leycec
