travis:
  secure:
    BINSTAR_TOKEN: SFOPTqi0x5sJhxgup9bOjmjpW5yVzpb/YJPNXxSOAIa1eBvcOsbUYXQtn9GoXUswdXG7O8E0nLsMmq0vzq6FOSOqxuDcsLDJ3wQR/JSSYQlZ3AEAtcS2TmXOjPBxjA7e0Aqz9y0CZpqpRdflaOl/bzJO0WROKLNWw6/mEhSATaFs0FxVJB77owUJJg9BXMQKws/CXetOX6T5cDPx7GjctG3tMeEESwNZ3R2g39QobifbGk/SpojhgnisuABg9AkYxCjfaJdpXbH7om9aD7jqlpv2QUFJKamClCqDuesmvO4OXcyqPMRAOfD6GdE5wRZhY5KutCzfDOLLqAGf2nXlWf9A2y5Myl6cGZ0tqoZfjt9om91sxFVYXPnLqVPJYyFr0dM1m/l98eM5nWGe+U11xbsr9cFzsOGdWj0urhwyKImmmB3aiDZywvyRCJ6lLnlXxZ2Lo2BT8JY66nhVBijuc8Fl/uypBcp/uUOrwxc4RaXbcRhLvpWy4As9AmMLE2h78H5RWXotrWgv9wV9Hq4xT6A9982UOQnsOKBbMU9Jqu98GK7lsBvKrmMBWFYXw1rECuyVdwmgLEwqlVMfyamf+/bUcR6qpLIHFZ6rICeiESkbTpVKLeE4GOV9hExYysm4M76plNJOGplj5lvf4D45EJ5rEXRkBH1w/2YpyZNQ96I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
