travis:
  secure:
    BINSTAR_TOKEN: HoBsZljKT1zuRVAo0oR2lQ0ZHJZiexryek5JhKUo60qVy0Sz9XkpkzXRNnk0su9IIW7kre+kjikcIuAqVvToqrRXhRqXsnnR3tLA2jdZ8nRedMMQohaFxFujsn9LmGhVRINh4IZFyrLcOZ+7z92mMlndw6cnFDrWkcz+6QxjsSGyc4TvM+wQNwG9Km/hefnd0jNFFyUkvNhAFO1OhdVMcf7heqwVuwZgcZqoqpJDQpM9UD5sgdJXKuvnZOtqtRM/WaLOUbsIvDMpyme8664xdOV7ogkt7WkYx0/fCwk5D0jk0K2aIFNFo9WY4m5/sIdJlInMqvns7KxOIdieaKJ/nbOMSIorxJQynkikxRycyoBddzesYbbIaCW5pkmwxNbT/EQTqSzUwNuT/WAszzvdirS7HASdX4fBMbywHIEpOHJxiuoYaGjV16HuylTZEXQkOtQx8ms/6KEwy2lhnmi0f16maZkiLqXyGArrx+77yGHWVEHxjCHZJcWj+OpZSBSfAIM6cr+h39qaF6MVltNmekkj+2XCkADukR7v2NoE+NOZLYBb3pF76dZ7s523OI10Jr2mAXKOoLX3VMlphj4/fpkv+DU18/RKhAl+lU2z0auJ1tylWuiIP6tgX2M+rp6k8000wL6LLb2cqNv2B0O/tDW2wOAiyIQlD133aD2hpz8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
